In [14]:
import numpy as np
import pandas as pd
import datetime
import math
from os import listdir
from os.path import isfile, join
import json

In [15]:
out='../output/'
pref='dam'
inp='../input/monthly/' + pref + '/'

In [16]:
dat=pd.DataFrame(columns=['date','hour','price','volume'])
onlyfiles = [f for f in listdir(inp) if isfile(join(inp, f))]
for f in onlyfiles:
    print(f.split('_'))
    if f.split('_')[0]==pref:
        if f.split('.')[1]=='csv':
            data = pd.read_csv(join(inp, f))
            dat=pd.concat([dat,data])
            
dat['date']=pd.to_datetime(dat.date,format="%Y-%m-%d")

dat.sort_index(inplace=True)
dat

['dam', '2021', '02.csv']
['dam', '2018', '12.csv']
['dam', '2022', '09.csv']
['dam', '2024', '07.json']
['dam', '2025', '04.csv']
['dam', '2018', '02.json']
['dam', '2016', '03.json']
['dam', '2018', '07.csv']
['dam', '2026', '01.csv']
['dam', '2018', '12.json']
['dam', '2017', '10.json']
['dam', '2020', '01.csv']
['dam', '2017', '04.csv']
['dam', '2020', '08.csv']
['dam', '2024', '03.csv']
['dam', '2019', '06.csv']
['dam', '2017', '06.json']
['dam', '2023', '08.json']
['dam', '2019', '08.csv']
['dam', '2021', '11.json']
['dam', '2020', '06.json']
['dam', '2025', '08.csv']
['dam', '2019', '09.json']
['dam', '2016', '08.csv']
['dam', '2024', '07.csv']
['dam', '2017', '07.json']
['dam', '2025', '06.csv']
['dam', '2020', '12.json']
['dam', '2024', '04.json']
['dam', '2021', '10.json']
['dam', '2022', '02.json']
['dam', '2017', '11.csv']
['dam', '2024', '09.json']
['dam', '2018', '09.csv']
['dam', '2019', '04.json']
['dam', '2019', '12.csv']
['dam', '2020', '12.csv']
['dam', '2016', '10.json']
['dam', '2023', '11.csv']
['dam', '2016', '12.json']
['dam', '2025', '05.csv']
['dam', '2016', '05.json']
['dam', '2020', '02.json']
['dam', '2018', '11.json']
['dam', '2023', '09.csv']
['dam', '2020', '10.json']
['dam', '2023', '03.json']
['dam', '2026', '07.json']
['dam', '2026', '05.csv']
['dam', '2021', '12.json']
['dam', '2021', '05.csv']
['dam', '2025', '03.json']
['dam', '2026', '03.json']
['dam', '2017', '01.csv']
['dam', '2022', '05.csv']
['dam', '2026', '06.csv']
['dam', '2021', '09.csv']
['dam', '2022', '01.csv']
['dam', '2017', '08.json']
['dam', '2021', '04.csv']
['dam', '2022', '03.csv']
['dam', '2018', '11.csv']
['dam', '2016', '02.json']
['dam', '2016', '09.csv']
['dam', '2022', '02.csv']
['dam', '2025', '07.csv']
['dam', '2016', '10.csv']
['dam', '2021', '06.json']
['dam', '2024', '11.csv']
['dam', '2023', '07.csv']
['dam', '2026', '09.json']
['dam', '2024', '05.csv']
['dam', '2024', '08.json']
['dam', '2024', '12.json']
['dam', '2018', '01.csv']
['dam', '2016', '04.json']
['dam', '2019', '02.json']
['dam', '2019', '03.csv']
['dam', '2025', '06.json']
['dam', '2017', '08.csv']
['dam', '2020', '04.json']
['dam', '2018', '04.json']
['dam', '2023', '05.csv']
['dam', '2016', '12.csv']
['dam', '2026', '08.json']
['dam', '2021', '02.json']
['dam', '2018', '05.json']
['dam', '2023', '02.json']
['dam', '2023', '01.json']
['dam', '2023', '10.csv']
['dam', '2019', '10.csv']
['dam', '2025', '07.json']
['dam', '2024', '01.json']
['dam', '2024', '10.json']
['dam', '2016', '11.csv']
['dam', '2020', '02.csv']
['dam', '2024', '09.csv']
['dam', '2025', '10.json']
['dam', '2019', '11.json']
['dam', '2019', '03.json']
['dam', '2021', '01.csv']
['dam', '2017', '02.csv']
['dam', '2019', '05.csv']
['dam', '2020', '08.json']
['dam', '2023', '11.json']
['dam', '2023', '12.json']
['dam', '2023', '02.csv']
['dam', '2026', '01.json']
['dam', '2020', '09.csv']
['dam', '2018', '06.json']
['dam', '2023', '01.csv']
['dam', '2020', '11.csv']
['dam', '2021', '05.json']
['dam', '2021', '03.csv']
['dam', '2016', '06.json']
['dam', '2017', '02.json']
['dam', '2025', '09.csv']
['dam', '2025', '09.json']
['dam', '2024', '04.csv']
['dam', '2017', '05.json']
['dam', '2019', '06.json']
['dam', '2023', '04.json']
['dam', '2020', '03.csv']
['dam', '2016', '01.csv']
['dam', '2020', '06.csv']
['dam', '2016', '04.csv']
['dam', '2017', '07.csv']
['dam', '2017', '12.json']
['dam', '2022', '10.json']
['dam', '2017', '09.csv']
['dam', '2022', '08.json']
['dam', '2021', '01.json']
['dam', '2020', '09.json']
['dam', '2016', '06.csv']
['dam', '2025', '11.json']
['dam', '2021', '08.csv']
['dam', '2019', '07.json']
['dam', '2026', '03.csv']
['dam', '2022', '09.json']
['dam', '2024', '10.csv']
['dam', '2023', '05.json']
['dam', '2018', '03.json']
['dam', '2021', '07.csv']
['dam', '2020', '04.csv']
['dam', '2022', '07.csv']
['dam', '2018', '04.csv']
['dam', '2016', '07.csv']
['dam', '2020', '07.json']
['dam', '2016', '08.json']
['dam', '2020', '03.json']
['dam', '2021', '12.csv']
['dam', '2016', '05.csv']
['dam', '2018', '10.json']
['dam', '2021', '06.csv']
['dam', '2023', '04.csv']
['dam', '2018', '07.json']
['dam', '2018', '08.csv']
['dam', '2026', '04.json']
['dam', '2025', '12.csv']
['dam', '2022', '10.csv']
['dam', '2026', '06.json']
['dam', '2019', '02.csv']
['dam', '2026', '07.csv']
['dam', '2026', '02.csv']
['dam', '2026', '08.csv']
['dam', '2023', '06.json']
['dam', '2022', '08.csv']
['dam', '2021', '04.json']
['dam', '2021', '03.json']
['dam', '2022', '12.json']
['dam', '2024', '01.csv']
['dam', '2019', '04.csv']
['dam', '2021', '07.json']
['dam', '2023', '06.csv']
['dam', '2017', '05.csv']
['dam', '2021', '08.json']
['dam', '2024', '02.csv']
['dam', '2018', '02.csv']
['dam', '2017', '06.csv']
['dam', '2019', '09.csv']
['dam', '2019', '11.csv']
['dam', '2018', '08.json']
['dam', '2024', '06.csv']
['dam', '2022', '06.csv']
['dam', '2025', '12.json']
['dam', '2016', '07.json']
['dam', '2020', '05.csv']
['dam', '2017', '12.csv']
['dam', '2020', '10.csv']
['dam', '2022', '07.json']
['dam', '2019', '07.csv']
['dam', '2024', '06.json']
['dam', '2023', '08.csv']
['dam', '2025', '05.json']
['dam', '2019', '08.json']
['dam', '2020', '05.json']
['dam', '2025', '10.csv']
['dam', '2019', '05.json']
['dam', '2016', '02.csv']
['dam', '2025', '01.json']
['dam', '2024', '02.json']
['dam', '2022', '03.json']
['dam', '2018', '09.json']
['dam', '2016', '01.json']
['dam', '2025', '08.json']
['dam', '2022', '11.csv']
['dam', '2017', '01.json']
['dam', '2017', '09.json']
['dam', '2020', '11.json']
['dam', '2020', '07.csv']
['dam', '2019', '01.csv']
['dam', '2025', '02.json']
['dam', '2021', '10.csv']
['dam', '2022', '04.csv']
['dam', '2018', '01.json']
['dam', '2018', '06.csv']
['dam', '2017', '04.json']
['dam', '2017', '11.json']
['dam', '2018', '05.csv']
['dam', '2025', '01.csv']
['dam', '2025', '04.json']
['dam', '2024', '12.csv']
['dam', '2022', '11.json']
['dam', '2018', '10.csv']
['dam', '2024', '08.csv']
['dam', '2024', '03.json']
['dam', '2016', '11.json']
['dam', '2022', '01.json']
['dam', '2017', '03.json']
['dam', '2024', '05.json']
['dam', '2022', '06.json']
['dam', '2016', '09.json']
['dam', '2018', '03.csv']
['dam', '2019', '12.json']
['dam', '2023', '12.csv']
['dam', '2025', '02.csv']
['dam', '2016', '03.csv']
['dam', '2019', '01.json']
['dam', '2021', '11.csv']
['dam', '2022', '04.json']
['dam', '2025', '11.csv']
['dam', '2024', '11.json']
['dam', '2020', '01.json']
['dam', '2022', '12.csv']
['dam', '2025', '03.csv']
['dam', '2021', '09.json']
['dam', '2023', '09.json']
['dam', '2026', '09.csv']
['dam', '2026', '02.json']
['dam', '2017', '10.csv']
['dam', '2022', '05.json']
['dam', '2023', '07.json']
['dam', '2017', '03.csv']
['dam', '2026', '05.json']
['dam', '2026', '04.csv']
['dam', '2023', '10.json']
['dam', '2023', '03.csv']
['dam', '2019', '10.json']

           date hour   price volume    zamg
0    2021-02-01    0   72.55  140.0     NaN
0    2019-08-01    0   54.05  485.9     NaN
0    2020-08-01    0   19.98  110.0     NaN
0    2022-12-01    0   226.1   27.0     NaN
0    2024-12-01    0  101.99    0.0  199.95
...         ...  ...     ...    ...     ...
1268 2024-01-31   19  199.94   68.0     NaN
1269 2024-01-31   20  200.25   80.0     NaN
1270 2024-01-31   21  199.07  100.0     NaN
1271 2024-01-31   22   158.0  101.0     NaN
1272 2024-01-31   23    62.0  161.0     NaN

[94752 rows x 5 columns]

In [17]:
hourly=dat.set_index(pd.DatetimeIndex(dat['date']))
hourly.sort_index(inplace=True)
hourly['year']=hourly.index.year
hourly['month']=hourly.index.month
hourly['day']=hourly.index.day
hourly['day_of_week']=hourly.index.dayofweek
hourly=hourly.drop(['date'],axis=1)
hourly['hour']=hourly['hour'].astype(int)
hourly

            hour   price volume  zamg  year  month  day  day_of_week
date
2016-01-01    13    45.1  323.0   NaN  2016      1    1            4
2016-01-01     2   40.06  495.6   NaN  2016      1    1            4
2016-01-01     1   40.08  486.6   NaN  2016      1    1            4
2016-01-01     3   40.08  496.6   NaN  2016      1    1            4
2016-01-01    11   48.02  315.0   NaN  2016      1    1            4
...          ...     ...    ...   ...   ...    ...  ...          ...
2026-09-30     5    35.0  558.8   NaN  2026      9   30            2
2026-09-30    19  186.06   92.1   NaN  2026      9   30            2
2026-09-30     8   45.07  266.6   NaN  2026      9   30            2
2026-09-30     1    35.0  526.4   NaN  2026      9   30            2
2026-09-30     3    35.0  535.4   NaN  2026      9   30            2

[94752 rows x 8 columns]

In [18]:
hourly['value']=hourly['price']*hourly['volume']
daily=hourly.groupby(['year','month','day']).sum().drop(['hour','day_of_week'],axis=1)
daily['price_weight_av']=daily['value']/daily['volume']
daily=daily.drop(['price'], axis=1)
daily['price_max']=hourly[['year','month','day','price']].groupby(['year','month','day']).max()
daily['price_min']=hourly[['year','month','day','price']].groupby(['year','month','day']).min()
daily['price_mean']=hourly[['year','month','day','price']].groupby(['year','month','day']).mean()

daily['power_max']=hourly[['year','month','day','volume']].groupby(['year','month','day']).max()
daily['power_min']=hourly[['year','month','day','volume']].groupby(['year','month','day']).min()
daily['power_mean']=hourly[['year','month','day','volume']].groupby(['year','month','day']).mean()

daily=daily.reset_index()
daily['date']=pd.to_datetime(daily.reset_index()[['year', 'month', 'day']])
daily=daily.set_index(['year','month','day'])
daily.sort_index(inplace=True)
daily

                 volume  zamg       value price_weight_av price_max price_min  \
year month day
2016 1     1     7873.8   0.0  336882.508       42.785251     60.08     35.09
           2     7319.5   0.0  345982.021       47.268532    118.49     40.03
           3     7198.7   0.0  351712.733       48.857812    118.47     44.06
           4     4457.0   0.0   225938.81       50.693024    177.66      46.7
           5     3750.4   0.0  179068.882       47.746609     181.4     42.06
...                 ...   ...         ...             ...       ...       ...
2026 9     26    9724.8   0.0  363238.202        37.35174     67.25     32.64
           27   10361.8   0.0  375079.373       36.198283      69.7     33.58
           28    8880.3   0.0  401815.594       45.247975    186.66     32.76
           29    8741.0   0.0  376130.673       43.030623    195.09     34.04
           30   10541.7   0.0  455089.459       43.170405    186.07     34.93

               price_mean power_max power_min  power_mean       date
year month day
2016 1     1      45.9825     502.9      53.0     328.075 2016-01-01
           2    54.114167     486.0      40.0  304.979167 2016-01-02
           3    54.959167     486.0      40.0  299.945833 2016-01-03
           4    80.164583     486.0       0.0  185.708333 2016-01-04
           5    84.503333     436.0       0.0  156.266667 2016-01-05
...                   ...       ...       ...         ...        ...
2026 9     26   38.436667     494.0     292.3       405.2 2026-09-26
           27   36.912917     550.0     277.3  431.741667 2026-09-27
           28    52.10875     568.0      35.3    370.0125 2026-09-28
           29   53.499583     554.0      34.0  364.208333 2026-09-29
           30   54.900833     600.0      51.0    439.2375 2026-09-30

[3926 rows x 11 columns]

In [19]:
hourly['cat']='off'

if (pref=='dam' or pref=='idm'):
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==6),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=7) & (hourly['hour']<=9),'cat']='morning'

    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=10) & (hourly['hour']<=16),'cat']='standard'

    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==17) & (hourly['month']>=6) & (hourly['month']<=8),'cat']='evening'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==17) & ((hourly['month']<=5) | (hourly['month']>=9)),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==18) & (hourly['month']<=3),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==18) & (hourly['month']>=4),'cat']='evening'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==19),'cat']='evening'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==20) & (hourly['month']<=3),'cat']='evening'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==20) & (hourly['month']>=4),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==21),'cat']='standard'

    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']>=7) & (hourly['hour']<=11),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']==17) & (hourly['month']>=6) & (hourly['month']<=8),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']==18) & (hourly['month']>=4),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']==19),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']==20) & (hourly['month']<=3),'cat']='standard'

if (pref=='fpm'):
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=6) & (hourly['hour']<=21),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']>=7) & (hourly['hour']<=11),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']>=18) & (hourly['hour']<=19),'cat']='standard'

if (pref=='fpw'):
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']==5),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=6) & (hourly['hour']<=8),'cat']='morning'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=9) & (hourly['hour']<=17),'cat']='standard'
    hourly.loc[(hourly['day_of_week']<5) & (hourly['hour']>=18) & (hourly['hour']<=19),'cat']='evening'
    
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']>=7) & (hourly['hour']<=11),'cat']='standard'
    hourly.loc[(hourly['day_of_week']==5) & (hourly['hour']>=18) & (hourly['hour']<=19),'cat']='standard'
    
hourly

,hour,price,volume,zamg,year,month,day,day_of_week,value,cat
date,,,,,,,,,,
2016-01-01,13,45.1,323.0,NaN,2016,1,1,4,14567.3,standard
2016-01-01,2,40.06,495.6,NaN,2016,1,1,4,19853.736,off
2016-01-01,1,40.08,486.6,NaN,2016,1,1,4,19502.928,off
2016-01-01,3,40.08,496.6,NaN,2016,1,1,4,19903.728,off
2016-01-01,11,48.02,315.0,NaN,2016,1,1,4,15126.3,standard
...,...,...,...,...,...,...,...,...,...,...
2026-09-30,5,35.0,558.8,NaN,2026,9,30,2,19558.0,off
2026-09-30,19,186.06,92.1,NaN,2026,9,30,2,17136.126,evening
2026-09-30,8,45.07,266.6,NaN,2026,9,30,2,12015.662,morning
2026-09-30,1,35.0,526.4,NaN,2026,9,30,2,18424.0,off
2026-09-30,3,35.0,535.4,NaN,2026,9,30,2,18739.0,off

In [20]:
daily['off_price_mean']=hourly.loc[hourly['cat']=='off'][['year','month','day','price']].groupby(['year','month','day']).mean()
daily['standard_price_mean']=hourly.loc[hourly['cat']=='standard'][['year','month','day','price']].groupby(['year','month','day']).mean()
daily['morning_price_mean']=hourly.loc[hourly['cat']=='morning'][['year','month','day','price']].groupby(['year','month','day']).mean()
daily['evening_price_mean']=hourly.loc[hourly['cat']=='evening'][['year','month','day','price']].groupby(['year','month','day']).mean()

daily['off_hour_count']=hourly.loc[hourly['cat']=='off'][['year','month','day','price']].groupby(['year','month','day']).count()
daily['standard_hour_count']=hourly.loc[hourly['cat']=='standard'][['year','month','day','price']].groupby(['year','month','day']).count()
daily['morning_hour_count']=hourly.loc[hourly['cat']=='morning'][['year','month','day','price']].groupby(['year','month','day']).count()
daily['evening_hour_count']=hourly.loc[hourly['cat']=='evening'][['year','month','day','price']].groupby(['year','month','day']).count()

daily['off_volume']=hourly.loc[hourly['cat']=='off'][['year','month','day','volume']].groupby(['year','month','day']).sum()
daily['standard_volume']=hourly.loc[hourly['cat']=='standard'][['year','month','day','volume']].groupby(['year','month','day']).sum()
daily['morning_volume']=hourly.loc[hourly['cat']=='morning'][['year','month','day','volume']].groupby(['year','month','day']).sum()
daily['evening_volume']=hourly.loc[hourly['cat']=='evening'][['year','month','day','volume']].groupby(['year','month','day']).sum()

daily['off_value']=hourly.loc[hourly['cat']=='off'][['year','month','day','value']].groupby(['year','month','day']).sum()
daily['standard_value']=hourly.loc[hourly['cat']=='standard'][['year','month','day','value']].groupby(['year','month','day']).sum()
daily['morning_value']=hourly.loc[hourly['cat']=='morning'][['year','month','day','value']].groupby(['year','month','day']).sum()
daily['evening_value']=hourly.loc[hourly['cat']=='evening'][['year','month','day','value']].groupby(['year','month','day']).sum()

daily

                 volume  zamg       value price_weight_av price_max price_min  \
year month day
2016 1     1     7873.8   0.0  336882.508       42.785251     60.08     35.09
           2     7319.5   0.0  345982.021       47.268532    118.49     40.03
           3     7198.7   0.0  351712.733       48.857812    118.47     44.06
           4     4457.0   0.0   225938.81       50.693024    177.66      46.7
           5     3750.4   0.0  179068.882       47.746609     181.4     42.06
...                 ...   ...         ...             ...       ...       ...
2026 9     26    9724.8   0.0  363238.202        37.35174     67.25     32.64
           27   10361.8   0.0  375079.373       36.198283      69.7     33.58
           28    8880.3   0.0  401815.594       45.247975    186.66     32.76
           29    8741.0   0.0  376130.673       43.030623    195.09     34.04
           30   10541.7   0.0  455089.459       43.170405    186.07     34.93

               price_mean power_max power_min  power_mean  ...  \
year month day                                             ...
2016 1     1      45.9825     502.9      53.0     328.075  ...
           2    54.114167     486.0      40.0  304.979167  ...
           3    54.959167     486.0      40.0  299.945833  ...
           4    80.164583     486.0       0.0  185.708333  ...
           5    84.503333     436.0       0.0  156.266667  ...
...                   ...       ...       ...         ...  ...
2026 9     26   38.436667     494.0     292.3       405.2  ...
           27   36.912917     550.0     277.3  431.741667  ...
           28    52.10875     568.0      35.3    370.0125  ...
           29   53.499583     554.0      34.0  364.208333  ...
           30   54.900833     600.0      51.0    439.2375  ...

               morning_hour_count evening_hour_count off_volume  \
year month day
2016 1     1                  3.0                2.0     3851.5
           2                  NaN                NaN     5969.5
           3                  NaN                NaN     7198.7
           4                  3.0                2.0     3828.0
           5                  3.0                2.0     3230.0
...                           ...                ...        ...
2026 9     26                 NaN                NaN     7537.0
           27                 NaN                NaN    10361.8
           28                 3.0                2.0     3654.0
           29                 3.0                2.0     3743.0
           30                 3.0                2.0     4330.8

               standard_volume morning_volume  evening_volume   off_value  \
year month day
2016 1     1            2920.3          993.0           109.0  152306.418
           2            1350.0            NaN             NaN  271567.021
           3               NaN            NaN             NaN  351712.733
           4             464.0          109.0            56.0   179880.68
           5             368.4          109.0            43.0   136366.42
...                        ...            ...             ...         ...
2026 9     26           2187.8            NaN             NaN   250426.23
           27              NaN            NaN             NaN  375079.373
           28           3367.3         1409.0           450.0    121440.2
           29           3356.0         1380.1           261.9   128981.51
           30           4892.5         1098.2           220.2    151536.0

                standard_value  morning_value evening_value
year month day
2016 1     1         131289.73        46741.0       6545.36
           2           74415.0            NaN           NaN
           3               NaN            NaN           NaN
           4          32852.59        8722.18       4483.36
           5         27912.322        8724.13       6066.01
...                        ...            ...           ...
2026 9     26       112811.972            NaN           NaN
           27              NaN            NaN           NaN
           28       134304.244       62328.15       83743.0
           29        138319.38      58272.625     50557.158
           30       213689.265      48892.501     40971.693

[3926 rows x 27 columns]

In [21]:
daily.to_csv(out + pref + '_daily.csv')

In [22]:
hourly.to_csv(out + pref + '_hourly.csv')

In [23]:
hourly_flat=hourly.reset_index().set_index(['date'])
hourly_slim=hourly_flat[['hour','price','volume','cat']]
hourly_slim

            hour   price volume       cat
date
2016-01-01    13    45.1  323.0  standard
2016-01-01     2   40.06  495.6       off
2016-01-01     1   40.08  486.6       off
2016-01-01     3   40.08  496.6       off
2016-01-01    11   48.02  315.0  standard
...          ...     ...    ...       ...
2026-09-30     5    35.0  558.8       off
2026-09-30    19  186.06   92.1   evening
2026-09-30     8   45.07  266.6   morning
2026-09-30     1    35.0  526.4       off
2026-09-30     3    35.0  535.4       off

[94752 rows x 4 columns]

In [24]:
hourly_slim.to_csv(out + pref + '_hourly_slim.csv')

In [25]:
monthly=daily.groupby(['year','month']).mean()
monthly=monthly.drop(columns=['morning_volume','off_volume','standard_volume','evening_volume','price_weight_av'])
monthly.rename(columns={'value':'value_mean','volume':'volume_mean','off_hour_count':'off_hour_mean','standard_hour_count':'standard_hour_mean','morning_hour_count':'morning_hour_mean','evening_hour_count':'evening_hour_mean'}, inplace=True)
monthly[['price_max','standard_price_max','off_price_max','morning_price_max','evening_price_max']]=daily.groupby(['year','month']).max()[['price_mean','standard_price_mean','off_price_mean','morning_price_mean','evening_price_mean']]
monthly[['price_min','standard_price_min','off_price_min','morning_price_min','evening_price_min']]=daily.groupby(['year','month']).min()[['price_mean','standard_price_mean','off_price_mean','morning_price_mean','evening_price_mean']]
monthly[['price_stdev','standard_price_stdev','off_price_stdev','morning_price_stdev','evening_price_stdev']]=daily.groupby(['year','month']).std()[['price_mean','standard_price_mean','off_price_mean','morning_price_mean','evening_price_mean']]

monthly

            volume_mean  zamg     value_mean   price_max  price_min  \
year month
2016 1      3877.909677   0.0  216538.697903   104.03625    45.9825
     2      3915.110345   0.0  263339.799483   111.84375  75.023333
     3      3004.254839   0.0  192831.319548  101.464167  60.115833
     4          1934.45   0.0  119384.364433  114.641667  40.925417
     5      1714.970968   0.0   95755.502839  104.820833  28.659583
...                 ...   ...            ...         ...        ...
2026 5      6160.070968   0.0  321780.347581   73.556667  42.390833
     6      4581.013333   0.0  208787.815433   67.129167  39.412917
     7      5646.809677   0.0  294934.056935       69.64  38.234167
     8      6560.522581   0.0  336811.350548   70.838333       34.2
     9           6389.3   0.0  282067.155367   57.552917  36.912917

           price_mean   power_max   power_min  power_mean                date  \
year month
2016 1      81.784624  362.651613   17.606452   161.57957 2016-01-16 00:00:00
     2      91.385273  367.837931   23.231034  163.129598 2016-02-15 00:00:00
     3      88.099516  285.867742   18.232258  125.177285 2016-03-16 00:00:00
     4      85.320472      183.97    7.236667   80.602083 2016-04-15 12:00:00
     5      78.638495  165.619355     4.66129   71.457124 2016-05-16 00:00:00
...               ...         ...         ...         ...                 ...
2026 5      58.437003  364.580645   66.945161  256.669624 2026-05-16 00:00:00
     6      53.448653      329.47   43.176667  190.875556 2026-06-15 12:00:00
     7      59.314328  363.822581   72.393548  235.283737 2026-07-16 00:00:00
     8      56.456559  417.745161   76.625806  273.355108 2026-08-16 00:00:00
     9      49.190806  377.223333  102.363333  266.220833 2026-09-15 12:00:00

            ... evening_price_max standard_price_min off_price_min  \
year month  ...
2016 1      ...           173.895          47.883636       39.4525
     2      ...           230.985         105.227143         50.48
     3      ...            159.31          79.008182      49.53125
     4      ...            192.77          48.655714      29.95625
     5      ...            180.21          38.725714       27.3675
...         ...               ...                ...           ...
2026 5      ...           200.435          40.087143     42.617083
     6      ...        155.053333             36.625     39.005625
     7      ...        151.626667             39.479        37.215
     8      ...             155.2            32.2575      35.17125
     9      ...           200.045          38.792727      32.92875

           morning_price_min  evening_price_min  price_stdev  \
year month
2016 1             47.046667              60.05    16.069174
     2            113.423333            120.085     9.513109
     3                 98.91              89.34    10.907181
     4             45.033333             114.79    17.997428
     5             42.956667             102.15    21.811428
...                      ...                ...          ...
2026 5                 45.45             88.295     9.267062
     6                 35.06         106.503333     6.886894
     7             60.543333             111.88    10.291987
     8                 42.13          72.776667    10.688983
     9             42.216667             118.31     6.863402

            standard_price_stdev  off_price_stdev morning_price_stdev  \
year month
2016 1                 16.331618         8.005807           27.324729
     2                  5.335687        10.070843           17.997176
     3                  8.540729         7.734006           15.293820
     4                 21.386705        12.512146           38.910060
     5                 23.322605        11.512988           26.538839
...                          ...              ...                 ...
2026 5                  7.243697         2.366404            5.321875
     6                  6.162765         1.946402            9.621754
     7                  6.534830         2.413835            4.553010
     8                  7.565408         3.820590            8.988987
     9                  3.619850         1.967750            1.939181

           evening_price_stdev
year month
2016 1               25.472109
     2               25.793166
     3               19.588256
     4               22.367452
     5               15.149957
...                        ...
2026 5               24.319262
     6               11.730533
     7               11.674828
     8               19.710885
     9               21.416124

[129 rows x 35 columns]

In [26]:
if (pref=='dam'):
    monthly['evening_days']=daily.loc[daily['evening_hour_count']>0].groupby(['year','month']).count()['volume']
    monthly['morning_days']=daily.loc[daily['morning_hour_count']>0].groupby(['year','month']).count()['volume']
    monthly['days']=daily.groupby(['year','month']).count()['volume']
    monthly[['volume','morning_volume','evening_volume','standard_volume','off_volume']]=daily.drop(columns=['date']).groupby(['year','month']).sum()[['volume','morning_volume','evening_volume','standard_volume','off_volume']]
    monthly[['value','morning_value','evening_value','standard_value','off_value']]=daily.drop(columns=['date']).groupby(['year','month']).sum()[['value','morning_value','evening_value','standard_value','off_value']]
    monthly[['off_hour_count','standard_hour_count', 'morning_hour_count', 'evening_hour_count']]=daily.drop(columns=['date']).groupby(['year','month']).sum()[['off_hour_count','standard_hour_count', 'morning_hour_count', 'evening_hour_count']]

    monthly['price_weight_mean']=monthly['value'] / monthly['volume']
    monthly['off_price_weight_mean']=monthly['off_value'] / monthly['off_volume']
    monthly['standard_price_weight_mean']=monthly['standard_value'] / monthly['standard_volume']
    monthly['morning_price_weight_mean']=monthly['morning_value'] / monthly['morning_volume']
    monthly['evening_price_weight_mean']=monthly['evening_value'] / monthly['evening_volume']

    monthly['off_power']=monthly['off_volume'] / monthly['off_hour_count']
    monthly['morning_power']=monthly['morning_volume'] / monthly['morning_hour_count']
    monthly['standard_power']=monthly['standard_volume'] / monthly['standard_hour_count']
    monthly['evening_power']=monthly['evening_volume'] / monthly['evening_hour_count']
monthly

            volume_mean  zamg     value_mean   price_max  price_min  \
year month
2016 1      3877.909677   0.0  216538.697903   104.03625    45.9825
     2      3915.110345   0.0  263339.799483   111.84375  75.023333
     3      3004.254839   0.0  192831.319548  101.464167  60.115833
     4          1934.45   0.0  119384.364433  114.641667  40.925417
     5      1714.970968   0.0   95755.502839  104.820833  28.659583
...                 ...   ...            ...         ...        ...
2026 5      6160.070968   0.0  321780.347581   73.556667  42.390833
     6      4581.013333   0.0  208787.815433   67.129167  39.412917
     7      5646.809677   0.0  294934.056935       69.64  38.234167
     8      6560.522581   0.0  336811.350548   70.838333       34.2
     9           6389.3   0.0  282067.155367   57.552917  36.912917

           price_mean   power_max   power_min  power_mean                date  \
year month
2016 1      81.784624  362.651613   17.606452   161.57957 2016-01-16 00:00:00
     2      91.385273  367.837931   23.231034  163.129598 2016-02-15 00:00:00
     3      88.099516  285.867742   18.232258  125.177285 2016-03-16 00:00:00
     4      85.320472      183.97    7.236667   80.602083 2016-04-15 12:00:00
     5      78.638495  165.619355     4.66129   71.457124 2016-05-16 00:00:00
...               ...         ...         ...         ...                 ...
2026 5      58.437003  364.580645   66.945161  256.669624 2026-05-16 00:00:00
     6      53.448653      329.47   43.176667  190.875556 2026-06-15 12:00:00
     7      59.314328  363.822581   72.393548  235.283737 2026-07-16 00:00:00
     8      56.456559  417.745161   76.625806  273.355108 2026-08-16 00:00:00
     9      49.190806  377.223333  102.363333  266.220833 2026-09-15 12:00:00

            ... evening_hour_count price_weight_mean off_price_weight_mean  \
year month  ...
2016 1      ...               42.0         55.839026             50.385088
     2      ...               42.0         67.262421             56.542839
     3      ...               46.0         64.186073             55.124423
     4      ...               42.0         61.714888             56.919792
     5      ...               44.0         55.835058             49.682582
...         ...                ...               ...                   ...
2026 5      ...               42.0         52.236468             46.499805
     6      ...               66.0         45.576775             43.821981
     7      ...               69.0          52.23021             42.431711
     8      ...               63.0         51.339104             43.123809
     9      ...               44.0         44.146801             35.746166

           standard_price_weight_mean  morning_price_weight_mean  \
year month
2016 1                      81.002858                  77.850006
     2                     106.547628                 129.026815
     3                      98.717668                 116.099471
     4                       104.1922                 104.410448
     5                     106.019186                  95.368696
...                               ...                        ...
2026 5                      49.148823                  56.828561
     6                        37.4155                   43.29662
     7                      53.561171                  68.158078
     8                      52.709588                  59.782681
     9                       44.39001                  44.618866

            evening_price_weight_mean   off_power  morning_power  \
year month
2016 1                     137.720998  272.092493      33.409524
     2                     156.801247   275.13253      12.280952
     3                     107.341031  214.125862      15.502899
     4                     139.262082   149.82063       7.793651
     5                     140.331232  130.040385      10.831818
...                               ...         ...            ...
2026 5                     191.134852  253.402949     294.969841
     6                     144.616967  188.167857     204.886364
     7                     135.029311  300.595058     192.494203
     8                     126.445293  333.210326     224.393651
     9                     180.233296  317.180588     246.254545

           standard_power evening_power
year month
2016 1          56.583459         37.35
     2          75.799614     42.580952
     3          56.748043     34.786957
     4          19.055263      4.438095
     5          18.262963      4.170455
...                   ...           ...
2026 5         274.243609    116.928571
     6         217.226587     90.036364
     7         188.846183    128.791304
     8           223.2524    171.506349
     9         226.271481    147.534091

[129 rows x 57 columns]

In [27]:
monthly['off_price_diff']=monthly['off_price_mean']-monthly['off_price_mean'].shift(1)
monthly['morning_price_diff']=monthly['morning_price_mean']-monthly['morning_price_mean'].shift(1)
monthly['standard_price_diff']=monthly['standard_price_mean']-monthly['standard_price_mean'].shift(1)
monthly['evening_price_diff']=monthly['evening_price_mean']-monthly['evening_price_mean'].shift(1)

#monthly['off_price_log_diff']=np.log10(monthly['off_price_mean'])-np.log10(monthly['off_price_mean']).shift(1)
#monthly['morning_price_log_diff']=np.log10(monthly['morning_price_mean'])-np.log10(monthly['morning_price_mean']).shift(1)
#monthly['standard_price_log_diff']=np.log10(monthly['standard_price_mean'])-np.log10(monthly['standard_price_mean']).shift(1)
#monthly['evening_price_log_diff']=np.log10(monthly['evening_price_mean'])-np.log10(monthly['evening_price_mean']).shift(1)

In [28]:
monthly.to_csv(out + pref + '_monthly.csv')

In [29]:
monthly_filt=monthly.reset_index().loc[monthly.reset_index()['year']>2019]
daily_filt=daily.reset_index().loc[daily.reset_index()['year']>2019]
hourly_filt=hourly.reset_index().loc[hourly.reset_index()['year']>2019]

In [30]:
monthly_filt.groupby(['month']).mean()[['volume','off_volume','standard_volume', 'morning_volume', 'evening_volume']]

,volume,off_volume,standard_volume,morning_volume,evening_volume
month,,,,,
1,120637.785714,63750.542857,41349.971429,12109.328571,3427.942857
2,97627.757143,53757.385714,31343.242857,9752.471429,2774.657143
3,82417.042857,45109.257143,27525.1,7094.2,2688.485714
4,100127.071429,55029.885714,33439.7,8906.414286,2751.071429
5,103246.128571,54524.8,35070.128571,10300.857143,3350.342857
6,91539.914286,45603.185714,30659.6,9321.771429,5955.357143
7,123971.428571,69602.285714,37109.514286,10501.4,6758.228571
8,136771.571429,77041.085714,41277.8,11323.442857,7129.242857
9,121071.2,68110.514286,38792.128571,10513.185714,3655.371429
10,108603.233333,63998.666667,33210.483333,8502.8,2891.283333
11,91875.5,57355.633333,25710.15,6407.933333,2401.783333
12,89445.45,47604.3,30466.4,8749.216667,2625.533333

In [31]:
calmonthly=daily_filt.groupby(['month']).mean().reset_index()
calmonthly=calmonthly.drop(columns=['year','day','volume','standard_volume','off_volume','morning_volume','evening_volume', 'off_hour_count', 'morning_hour_count', 'standard_hour_count','evening_hour_count'])
calmonthly.rename(columns={'value':'value_mean','volume':'volume_mean','price_weight_av': 'price_weight_mean'}, inplace=True)
calmonthly.set_index('month',inplace=True)

calmonthly[['price_median', 'off_price_median','standard_price_median', 'morning_price_median', 'evening_price_median']]=daily_filt.groupby(['month']).median()[['price_mean','off_price_mean','standard_price_mean', 'morning_price_mean', 'evening_price_mean']]
calmonthly[['price_stdev', 'off_price_stdev','standard_price_stdev', 'morning_price_stdev', 'evening_price_stdev']]=daily_filt.groupby(['month']).std()[['price_mean','off_price_mean','standard_price_mean', 'morning_price_mean', 'evening_price_mean']]

calmonthly[['volume', 'off_volume','standard_volume', 'morning_volume', 'evening_volume']]=monthly_filt.groupby(['month']).mean()[['volume','off_volume','standard_volume', 'morning_volume', 'evening_volume']]
calmonthly[['value', 'off_value','standard_value', 'morning_value', 'evening_value']]=monthly_filt.groupby(['month']).mean()[['value','off_value','standard_value', 'morning_value', 'evening_value']]
calmonthly[['off_hour_count','standard_hour_count', 'morning_hour_count', 'evening_hour_count']]=monthly_filt.groupby(['month']).mean()[['off_hour_count','standard_hour_count', 'morning_hour_count', 'evening_hour_count']]
calmonthly[['off_power','standard_power', 'morning_power', 'evening_power']]=monthly_filt.groupby(['month']).mean()[['off_power','standard_power', 'morning_power', 'evening_power']]

calmonthly

,zamg,value_mean,price_weight_mean,price_max,price_min,price_mean,power_max,power_min,power_mean,date,...,evening_volume,value,off_hour_count,standard_hour_count,morning_hour_count,evening_hour_count,off_power,standard_power,morning_power,evening_power
month,,,,,,,,,,,,,,,,,,,,,
1,704.625576,245494.954387,69.366832,208.306866,40.566498,80.361137,245.693548,46.66129,146.558811,2023-01-16 03:25:42.857142,...,3427.942857,7610343.586,394.714286,302.714286,73.285714,48.857143,161.426707,135.323344,163.279546,70.538458
2,511.608081,281413.412409,82.99629,234.923081,48.89803,94.192014,235.213131,38.119697,143.811932,2023-02-11 02:18:10.909091,...,2774.657143,7959979.379571,327.571429,250.571429,60.428571,40.285714,164.593224,124.688442,160.910125,68.873741
3,426.274654,206138.509544,85.316295,207.007281,58.06765,93.972177,181.479263,33.135945,110.775595,2023-03-16 10:17:08.571428,...,2688.485714,6390293.795857,359.714286,273.571429,66.428571,44.285714,125.584351,100.558164,106.769971,60.560053
4,627.189048,211109.310605,79.26373,200.89219,48.112286,85.103683,218.896667,37.892857,139.065377,2023-04-15 22:17:08.571428,...,2751.071429,6333279.318143,344.857143,267.285714,64.714286,43.142857,160.227034,124.939271,137.611186,63.732811
5,477.776959,192600.354502,60.419133,186.04894,35.442488,68.6476,225.553917,48.593088,138.771678,2023-05-16 10:17:08.571428,...,3350.342857,5970610.989571,362.285714,272.428571,65.571429,43.714286,150.059976,129.22855,157.939919,76.713699
6,401.492381,208221.149195,78.397469,199.911714,41.93219,83.466103,224.452381,45.363333,127.13877,2023-06-15 22:17:08.571428,...,5955.357143,6246634.475857,341.714286,248.857143,64.714286,64.714286,134.090468,122.608435,143.176922,91.754803
7,925.669539,311075.780627,82.378755,217.55894,44.739447,90.303767,273.251613,59.397235,166.628264,2023-07-16 10:17:08.571428,...,6758.228571,9643349.199429,352.000000,258.285714,66.857143,66.857143,198.244839,143.791325,156.564501,101.482816
8,572.669263,334397.829912,78.019862,227.101014,43.186175,87.952775,294.418433,69.093548,183.832757,2023-08-16 10:17:08.571428,...,7129.242857,10366332.727286,357.714286,255.142857,65.571429,65.571429,214.411372,161.822798,173.152637,108.646151
9,767.439095,317186.188719,85.970481,227.789095,49.047429,98.271185,259.721429,62.061429,168.154444,2023-09-15 22:17:08.571428,...,3655.371429,9515585.661571,343.571429,267.857143,65.142857,43.428571,198.970111,144.4568,160.866193,83.499242
10,920.875538,348373.924091,109.719223,270.209785,61.502312,124.922171,252.45914,45.642473,145.994655,2023-04-16 20:00:00.000000,...,2891.283333,10799591.646833,360.333333,273.500000,66.000000,44.000000,177.949209,121.697701,129.286026,66.52583
11,1073.293833,340797.449617,138.932968,279.022833,82.076056,151.818653,226.405,38.735556,127.604861,2023-05-17 08:00:00.000000,...,2401.783333,10223923.4885,348.333333,265.000000,64.000000,42.666667,163.332183,97.614683,101.217506,55.812143
12,948.590323,228081.018118,92.379502,225.76629,56.747742,106.528434,204.00914,34.934946,120.222379,2023-06-16 20:00:00.000000,...,2625.533333,7070511.561667,356.333333,276.000000,67.000000,44.666667,134.500734,110.117688,130.116746,58.984505

In [32]:
calmonthly.to_csv(out + pref + '_calmonthly.csv')

In [33]:
calmonthly_hours=hourly_filt.drop(columns=['date','cat']).groupby(['month','hour']).mean()
calmonthly_hours=calmonthly_hours.drop(columns=['year','day','day_of_week'])
calmonthly_hours

                 price      volume        zamg        value
month hour
1     0      47.975732  164.836402  153.095806  7050.968674
      1      46.052929  173.297908  152.824839  7098.206766
      2      45.067071  178.376151  151.523871  7141.737255
      3      44.703264  179.072385  154.572258  7117.589335
      4      45.985063  183.312552  176.710968  7515.594418
...                ...         ...         ...          ...
12    19     218.22172   52.636022  349.575484  9198.067242
      20    195.739516   55.974194  341.976129  8345.044188
      21    149.460323    92.54086  277.642903  9710.734473
      22     86.154677  123.412366  193.753226  8383.269925
      23     73.180054  132.953763  171.112258  7669.809812

[288 rows x 4 columns]

In [34]:
calmonthly_hours.to_csv(out + pref + '_calmonthly_hours.csv')

In [35]:
yearly_calmonthly_hours=hourly_filt.drop(columns=['date','cat']).groupby(['year','month','hour']).mean()
yearly_calmonthly_hours=yearly_calmonthly_hours.drop(columns=['day','day_of_week'])
yearly_calmonthly_hours

                      price      volume  zamg         value
year month hour
2020 1     0      46.363548  156.645161   NaN   7225.481613
           1      43.721935  166.580645   NaN   7316.026129
           2      42.424516   170.16129   NaN   7284.921613
           3      42.173226   169.83871   NaN   7233.679032
           4      42.779355  176.035484   NaN   7619.790323
...                     ...         ...   ...           ...
2026 9     19    147.126667      161.28   NaN  22275.935967
           20        67.762  141.253333   NaN   7987.852067
           21        42.084  262.913333   NaN    10749.7292
           22     35.743333  313.956667   NaN  11083.345333
           23        35.482      314.29   NaN  11025.708333

[1944 rows x 4 columns]

In [36]:
yearly_calmonthly_hours.to_csv(out + pref + '_yearly_calmonthly_hours.csv')

In [38]:
from statsmodels.tsa.stattools import pacf

In [39]:
pacfs=pd.DataFrame(data={'standard': pacf(monthly.reset_index()['standard_price_mean'], nlags=14)})
pacfs['evening']= pacf(monthly.reset_index()['evening_price_mean'], nlags=14)
pacfs['morning']= pacf(monthly.reset_index()['morning_price_mean'], nlags=14)
pacfs['off']= pacf(monthly.reset_index()['off_price_mean'], nlags=14)
pacfs

    standard   evening   morning       off
0   1.000000  1.000000  1.000000  1.000000
1   0.755010  0.825368  0.744688  0.794257
2  -0.034892  0.001679 -0.002820 -0.069871
3   0.170193  0.119917  0.066379  0.299539
4   0.014428  0.173479 -0.053582  0.174702
5  -0.057827  0.023319 -0.152214 -0.093908
6  -0.075457  0.003490 -0.243896  0.084762
7   0.218257  0.025335  0.320121  0.132818
8  -0.031731  0.082267  0.127846 -0.075624
9   0.012663  0.098275 -0.091489  0.071915
10  0.104734 -0.133742  0.019985  0.141392
11  0.149822  0.202272  0.087673  0.097173
12 -0.015003 -0.174791 -0.065548  0.128161
13 -0.196863  0.133929 -0.216472 -0.218289
14 -0.187004 -0.097008 -0.017002 -0.214763

In [40]:
pacfs.to_csv(out + pref + '_pacfs.csv')